import os
SITE=os.environ.get('SITE','/tmp/site')
exec(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'etkflow.py')).read().split("res=[]")[0])
import json
res=[]
def ok(c,m): res.append(bool(c)); print(('  PASS ' if c else '  FAIL ')+m)
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=b.new_context(viewport={'width':820,'height':1180}); ctx.route('**/*supabase*', lambda r: r.abort()); ctx.expose_function('__dbop', dbop); ctx.add_init_script(MOCK)
    errs=[]; c=ctx.new_page(); c.on('pageerror', lambda e: errs.append(str(e))); c.goto('file://'+SITE+'/showcomm/etk/index.html?role=crew'); c.wait_for_timeout(1000)
    grid=lambda: c.evaluate("document.getElementById('crew-step-device').classList.contains('active')")
    c.click('.crew-device-card:has-text("BP05")'); c.wait_for_timeout(200); c.fill('#crew-claim-name','Ann'); c.click('#btn-crew-claim-submit'); c.wait_for_timeout(1200)
    print('1. Nothing unsent')
    ok(c.is_visible('#crew-home-back') and 'ALL BELTPACKS' in c.inner_text('#crew-home-back').upper(),'"← All beltpacks" at the top of the pack screen')
    c.click('#crew-home-back'); c.wait_for_timeout(600)
    ok(grid() and c.query_selector('#crew-leave-confirm') is None,'goes straight back to the grid, no questions')
    cl=[x for x in STORE['device_claims'] if x['device_id']=='BP05']
    ok(cl and cl[-1]['status'] in ('pending','confirmed'),'BP05 is still claimed by Ann')
    print('2. Tapped the wrong pack: open it, back out')
    c.click('.crew-device-card:has(.crew-device-card-id:text-is("BP05"))'); c.wait_for_timeout(1200)
    ok(c.is_visible('#crew-home-back'),'reopening a claimed pack also has Back'); c.click('#crew-home-back'); c.wait_for_timeout(600)
    ok(grid(),'back on the grid')
    print('3. Unsent picks')
    c.click('.crew-device-card:has(.crew-device-card-id:text-is("BP05"))'); c.wait_for_timeout(1200)
    c.click('#crew-cell-0'); c.wait_for_timeout(200); c.click('.crew-picker-opt:text-is("CAMS")'); c.wait_for_timeout(200)
    before=len(STORE['key_requests'])
    c.click('#crew-home-back'); c.wait_for_timeout(300)
    ok(c.is_visible('#crew-leave-confirm') and 'Leave BP05' in c.inner_text('#crew-leave-confirm') and '1 change' in c.inner_text('#crew-leave-confirm'),'asks: "Leave BP05 without sending?" (1 change)')
    c.click('#crew-leave-keep'); c.wait_for_timeout(300)
    ok(not grid() and 'CAMS' in c.inner_text('#crew-cell-0'),'Keep editing: stays put, CAMS pick still there')
    c.click('#crew-home-back'); c.wait_for_timeout(300); c.click('#crew-leave-discard'); c.wait_for_timeout(700)
    ok(grid(),'Discard changes: back to the grid')
    ok(len(STORE['key_requests'])==before,'nothing was sent to the TM')
    c.click('.crew-device-card:has(.crew-device-card-id:text-is("BP05"))'); c.wait_for_timeout(1200)
    ok('CAMS' not in c.inner_text('#crew-cell-0'),'reopening BP05: the discarded pick is gone')
    ok(not errs,'no page errors '+str(errs[:2]))
    b.close()
print(f"\n{sum(res)} passed, {len(res)-sum(res)} failed")
