import os
SITE=os.environ.get('SITE','/tmp/site')
exec(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'etkflow.py')).read().split("res=[]")[0])
import json
res=[]
def ok(c,m): res.append(bool(c)); print(('  PASS ' if c else '  FAIL ')+m)
STORE.setdefault('bp_custody',[])
STORE['device_claims'].append({'id':'c5','production_id':'ETK','device_type':'beltpack','device_id':'BP05','crew_name':'Ann','crew_position':'','status':'confirmed','claimed_at':iso(now-datetime.timedelta(hours=1))})
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=b.new_context(viewport={'width':820,'height':1180}, has_touch=True); ctx.route('**/*supabase*', lambda r: r.abort()); ctx.expose_function('__dbop', dbop); ctx.add_init_script(MOCK)
    errs=[]; c=ctx.new_page(); c.on('pageerror', lambda e: errs.append(str(e))); c.clock.install(); c.goto('file://'+SITE+'/showcomm/etk/index.html?role=crew'); c.clock.run_for(1500)
    tile=lambda bp: c.query_selector(f'#etk-deploy-grid .etk-deploy-tile:has(.etk-deploy-id:text-is("{bp}"))')
    print('1. Tabs')
    ok(c.is_visible('#crew-tabs') and 'active' in c.get_attribute('#crew-tabs [data-tab="claim"]','class'),'Claim | Deploy tabs on the pack grid, Claim selected')
    c.tap('#crew-tabs [data-tab="deploy"]'); c.clock.run_for(800)
    ok(c.evaluate("_crewStep")=='deploy' and len(c.query_selector_all('#etk-deploy-grid .etk-deploy-tile'))==24,'Deploy shows all 24 packs')
    out0=c.evaluate("_etkDeployBps.filter(etkIsOut).length")
    ok(c.inner_text('#etk-count-out').strip()==str(out0) and c.inner_text('#etk-count-in').strip()==str(24-out0),f'counts match the data: {out0} out, {24-out0} in')
    ok('Ann' in tile('BP05').inner_text() and 'Spare' in tile('BP06').inner_text(),'claimed packs show the holder, others "Spare"')
    print('2. Check out and back in')
    tile('BP05').tap(); c.clock.run_for(800)
    r=STORE['bp_custody'][-1]
    ok(r['device_id']=='BP05' and r['action']=='deployed' and r['crew_name']=='Ann','BP05 checked out (recorded with Ann)')
    ok('out' in tile('BP05').get_attribute('class') and c.inner_text('#etk-count-out').strip()==str(out0+1),'tile turns Out, OUT count goes up by one')
    ok('checked out' in c.inner_text('#crew-toast') and 'tap again' in c.inner_text('#crew-toast'),'confirmation: "'+c.inner_text('#crew-toast')+'"')
    ok(c.query_selector('#etk-undo') is None,'no Undo button on the cart')
    tile('BP05').tap(); c.clock.run_for(800)
    ok(STORE['bp_custody'][-1]['action']=='returned' and 'out' not in tile('BP05').get_attribute('class'),'tap again: checked back in')
    print('3. TM and cart stay in sync')
    tm=ctx.new_page(); tm.goto('file://'+SITE+'/showcomm/etk/index.html?role=tm'); tm.wait_for_timeout(700)
    tm.fill('#login-username','tm'); tm.fill('#login-pw','showcomm'); tm.click('#btn-login'); tm.wait_for_timeout(1500)
    tm.evaluate("setTMView('deploy')"); tm.wait_for_timeout(900)
    tm.click('#etk-deploy-grid .etk-deploy-tile:has(.etk-deploy-id:text-is("BP07"))'); tm.wait_for_timeout(700)
    c.clock.run_for(16000)
    ok('out' in tile('BP07').get_attribute('class'),'TM checks out BP07 → the cart shows it Out on its next refresh')
    print('4. Tabs inside a pack, and idle')
    c.tap('#crew-tabs [data-tab="claim"]'); c.clock.run_for(800)
    c.tap('.crew-device-card:has(.crew-device-card-id:text-is("BP05"))'); c.clock.run_for(1200)
    ok(not c.is_visible('#crew-tabs') and c.is_visible('#crew-home-back'),'inside a pack: tabs hidden, Back shown')
    c.tap('#crew-home-back'); c.clock.run_for(600)
    c.tap('#crew-tabs [data-tab="deploy"]'); c.clock.run_for(800)
    c.clock.run_for(61000)
    ok(c.evaluate("_crewStep")=='device' and 'active' in c.get_attribute('#crew-tabs [data-tab="claim"]','class'),'a minute idle on Deploy → back to Claim')
    ok(not errs,'no page errors '+str(errs[:2]))
    b.close()
print(f"\n{sum(res)} passed, {len(res)-sum(res)} failed")
