import os
SITE=os.environ.get('SITE','/tmp/site')
exec(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'etkflow.py')).read().split("res=[]")[0])
import json
res=[]
def ok(c,m): res.append(bool(c)); print(('  PASS ' if c else '  FAIL ')+m)
N=lambda m: iso(now-datetime.timedelta(minutes=m))
J=lambda *e: json.dumps([dict(keyIndex=k,label=f'Key {k+1}',note=n) for k,n in e])
STORE.setdefault('bp_custody',[])
STORE['device_claims'].append({'id':'c5','production_id':'ETK','device_type':'beltpack','device_id':'BP05','crew_name':'Ann','crew_position':'','status':'confirmed','claimed_at':N(60)})
STORE['key_requests']+=[{'id':'f5','production_id':'ETK','device_id':'BP05','status':'fulfilled','requester_role':'crew','created_at':N(50),'note':J((0,'CAMS (PL)'))},
                        {'id':'o5','production_id':'ETK','device_id':'BP05','status':'open','requester_role':'crew','created_at':N(5),'note':J((1,'TECH (PL)'))}]
STORE['bp_custody'].append({'id':'d5','production_id':'ETK','device_id':'BP05','action':'deployed','crew_name':'Ann','created_at':N(40)})
with sync_playwright() as pw:
    b=pw.chromium.launch(); ctx=b.new_context(viewport={'width':820,'height':1180}, has_touch=True); ctx.route('**/*supabase*', lambda r: r.abort()); ctx.expose_function('__dbop', dbop); ctx.add_init_script(MOCK)
    errs=[]; c=ctx.new_page(); c.on('pageerror', lambda e: errs.append(str(e))); c.goto('file://'+SITE+'/showcomm/etk/index.html?role=crew'); c.wait_for_timeout(1200)
    c.tap('.crew-device-card:has(.crew-device-card-id:text-is("BP05"))'); c.wait_for_timeout(1300)
    print('1. The pack screen')
    ok(c.inner_text('#crew-home-holder')=='Ann' and c.is_visible('#crew-rename-btn'),'header shows "Ann" with a Rename button')
    print('2. Guards')
    c.tap('#crew-rename-btn'); c.wait_for_timeout(200)
    ok(c.evaluate("document.activeElement.id")=='crew-rename-input' and c.evaluate("(()=>{const i=document.getElementById('crew-rename-input'); return i.selectionStart===0 && i.selectionEnd===i.value.length})()"),'name field focused and selected, ready to type over')
    c.fill('#crew-rename-input','   '); c.tap('#crew-rename-save'); c.wait_for_timeout(200)
    ok('Enter a name' in c.inner_text('#crew-rename-err'),'blank name: "Enter a name."')
    c.fill('#crew-rename-input','Ann'); c.tap('#crew-rename-save'); c.wait_for_timeout(300)
    ok(c.query_selector('#crew-rename') is None and STORE['device_claims'][-1]['crew_name']=='Ann','same name: closes, nothing written')
    c.tap('#crew-rename-btn'); c.wait_for_timeout(200); c.evaluate("_etkOnline=false; 0"); c.fill('#crew-rename-input','Ben'); c.tap('#crew-rename-save'); c.wait_for_timeout(300)
    ok('No connection' in c.inner_text('#crew-rename-err') and STORE['device_claims'][-1]['crew_name']=='Ann','offline: says so, nothing changes')
    c.evaluate("_etkOnline=true; 0")
    print('3. Rename Ann → Ben (Enter key)')
    claim_before={k:STORE['device_claims'][-1][k] for k in ('id','claimed_at','status')}
    c.fill('#crew-rename-input','  Ben   Ortiz '); c.press('#crew-rename-input','Enter'); c.wait_for_timeout(800)
    cl=STORE['device_claims'][-1]
    ok(cl['crew_name']=='Ben Ortiz','saved as "Ben Ortiz" (extra spaces tidied)')
    ok({k:cl[k] for k in ('id','claimed_at','status')}==claim_before,'same claim: id, claim time and status untouched')
    ok(c.inner_text('#crew-home-holder')=='Ben Ortiz' and c.inner_text('#crew-topbar-name')=='Ben Ortiz','pack header and top bar show Ben Ortiz')
    ok('Ann → Ben Ortiz' in c.inner_text('#crew-toast'),'note: "'+c.inner_text('#crew-toast')+'"')
    ok(len([r for r in STORE['key_requests'] if r['device_id']=='BP05'])==2,'keys and the pending request untouched')
    print('4. Everyone else sees it')
    tm=ctx.new_page(); tm.goto('file://'+SITE+'/showcomm/etk/index.html?role=tm'); tm.wait_for_timeout(700)
    tm.fill('#login-username','tm'); tm.fill('#login-pw','showcomm'); tm.click('#btn-login'); tm.wait_for_timeout(1500)
    q=tm.query_selector('#etk-queue-item-BP05')
    ok(q is not None and 'Ben Ortiz' in q.inner_text() and 'TECH' in q.inner_text(),'TM queue: BP05 · Ben Ortiz, TECH still pending')
    keys=tm.evaluate("etkPackKeys(_etkBpData.BP05.reqs,_etkBpData.BP05.claim).map(k=>k.on&&k.on.label)")
    ok(keys[0]=='CAMS','CAMS still on key 1 '+str(keys))
    tm.evaluate("setTMView('deploy')"); tm.wait_for_timeout(900)
    t=tm.inner_text('#etk-deploy-grid .etk-deploy-tile:has(.etk-deploy-id:text-is("BP05"))')
    ok('Ben Ortiz' in t and 'OUT' in t.upper(),'Deploy: BP05 · Ben Ortiz, still Out')
    ok(not errs,'no page errors '+str(errs[:2]))
    b.close()
print(f"\n{sum(res)} passed, {len(res)-sum(res)} failed")
